package in.codegram.phonebookapp.domain;

public class Person {
	/**
	 * id of the user PK, autogenerated
	 */
	private Integer id;
	/**
	 * name of the user
	 */
	private String name;
	/**
	 * phone no of the user
	 */
	private String phone;
	/**
	 * email of the user
	 */
	private String email;
	/**
	 * address of the user- city
	 */
	private String address;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
